# .sops.yaml

keys:
  - &user_alex age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
  - &mercury_root age16uv00hxnmkf2pqkldezs8ym3f2nrm6s0x7xhkpnxvu329c6srscsqr4jj3
creation_rules:
  - path_regex: secrets/primary/[^/]+\.yaml
    key_groups:
    - age:
      - *user_alex
  - path_regex: secrets/mercury/[^/]+\.yaml
    key_groups:
    - age:
      - *mercury_root
