# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  environment.etc."crypttab".text = ''
    luks-drive-a UUID=3e36ef9b-21f1-46fe-bf1c-b6dfe8cf8e5d /persist/luks/drive_a nofail,noauto
    luks-drive-movies UUID=25516f06-b154-4c9f-8b47-abe539d1b9a7 /persist/luks/movies nofail,noauto
  '';
  
  fileSystems."/" =
    { device = "none";
      neededForBoot = true;
      fsType = "tmpfs";
      options = [ "size=3G" "mode=755" ]; # mode=755 so only root can write to those files
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9ED1-117E";
      fsType = "vfat";
      options = [ "nodev" "nosuid" "noexec" "relatime"
      	"fmask=0077" "dmask=0077"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/dd7eb714-107b-449a-9d4e-d6085eb6cf39";
      fsType = "xfs";
      options = [ "relatime" ];
    };
  
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/afa3b6a2-e67c-4365-b930-a95ca283f1a0";
      fsType = "xfs";
    };
    
  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/66f017e2-31aa-4a04-abe5-33539dd6e22e";
      neededForBoot = true;
      fsType = "xfs";
    };

  fileSystems."/mnt/drive_a" =
    { device = "/dev/mapper/luks-drive-a";
      fsType = "xfs";
      options = [ "nodev" "nosuid" "noexec" "relatime"
      		"x-gvfs-name=Drive%20A" "x-gvfs-show" "x-systemd.automount" 
      		"noauto"
      ];
    };
  fileSystems."/mnt/movies" =
    { device = "/dev/mapper/luks-drive-movies";
      fsType = "xfs";
      options = [ "nodev" "nosuid" "noexec" "relatime"
      		"ro" # Make it read-only
      		"x-gvfs-name=Movies" "x-gvfs-show" "x-systemd.automount" "noauto"
      ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.powerOnBoot = false;
}
