users:
    root:
        hashedPassword: ENC[AES256_GCM,data:P5fb7+X8mJ6VhYABWHWMb55XVzu+ndkbDuIUXvg2y7YycIZtP2mgfhaKgPAMRZraBD04qmrY+XLb2Egngdj6BzaL79FsUKghXg==,iv:sZdytax6OZQO22vS9gxkRLLZcSahtsTBeKtSn1HVm88=,tag:xsOTv632Drn0ajeY2MlJsw==,type:str]
    warden:
        hashedPassword: ENC[AES256_GCM,data:FOSpIeielc8QmPABKwvMHi0yZ2lEhsJKVzR9iTy4mHGHSs2FodZzy07trlJcLQM7wvBVVYyoVScfV36+75rj/yjdjrMn2gIDWw==,iv:20hnL9L64Uij4TwXKTYtpSG3Fvo3Am3gKIRhMX0VPJk=,tag:JU7jh83fwQHdVogKzY1Www==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4enZGRzdZd09yYXlHTHZy
            eXZQbWF4R0k0N3pFUFVtSVc3QzNVRE56RXhFCk0wOVo5emVISjhUYnc0eVlaYzFQ
            d2J2cUh5S1UxdVl5dXVMbU1mcWxaRTQKLS0tIENKeFUzY3J0QVhGTEZQOEU5K0tF
            ajE5TW5CeGNEbzd5OFJaZ3FXZXovbEUKiDMlVU1k26eHjXVV1zHNguuwUvcYXx/D
            SvfQFD9bB4BFOieaLgKFKJnDc/ImXFFVFLJLCGIBnfYIddtQxEVMdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uv00hxnmkf2pqkldezs8ym3f2nrm6s0x7xhkpnxvu329c6srscsqr4jj3
    lastmodified: "2026-07-12T15:54:54Z"
    mac: ENC[AES256_GCM,data:fbeCdd7UM97KFCYXpiip0gVqDi68qZXjMQxGL1nXvHyCUkybRVk0LfXNnMVW4j6iqc2HZCgvMreN/GiMF005Xwklpiafuim9hTl9LNeP5lN1fUMcxcPwfafX5A2z+MK9molt40iy61jGu6T7960a5WEZTrQ55J26oektizxypkM=,iv:/lnW2UOPmj2uTH1ea/+2f9euwtqtX9i9NiakP1UvTG8=,tag:NJyoRsep2A9llZD+F+kMWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
