users:
    root:
        hashedPassword: ENC[AES256_GCM,data:yEqJU+y+uElHIOkrcwJLJ3EQI8nX5orgvPfdjibswWm4DkqaVrMGSDW8SIp+aBcE9Ytr+ceDWV9w+ncIHzRVod174eVug6ZG7w==,iv:Vj/mU92JdielEwuY3ih38Nc3MNvPURnR9BjxqZ3nnmc=,tag:Lc2S/L2N1gl1cuYAzZ+ewg==,type:str]
    warden:
        hashedPassword: ENC[AES256_GCM,data:CgDL8Vf4diByfKkl8OhhpXzBkQz3N06/G7H7Y0LgqWNC8L/ukuDDvA5qArlyoiPwNwyF3dLN+E6eyYUIzGSkVXx8zpYLGkiG6A==,iv:ic9JdPi8nL8IiEBLWO9Wy3YZ0ZZFi28l9YAatqcn9eQ=,tag:xjeAsBg/AzDDsWeF/FZngA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMDhmQldKTzFSTTBVWWI5
            MmVRK2V4Y0dZUW94aUgrc3hRTGhqWWRVU3hNCkpncmNBUmE3bm51bWc1elltUGxQ
            VzZ2dmJyamFNdTA5RndmRUY5Um9KeVUKLS0tIFZjOFJ0RHZYc0xKUWFOckg4bDJl
            VEQxR2x3UEt3M1JGQ21CSmhaZjhkN2cK//YPrw56EHw58bxLddeo6+shTFlj2Q2W
            +IFN39A1wl2PcTDtCNtCiYZte8Dy9nXsuDqdaD9VzBRW37Y8NhPERQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ldgwrdexcm4tqhruyxat2e72nss77a77uz55wwsgfecfkvdly52svfgjtz
    lastmodified: "2026-07-12T15:54:55Z"
    mac: ENC[AES256_GCM,data:XfSUMHtsCNgYfaDX2w/UmAio1A1WnDGfy/XxEDcyyxOO+xIwww5dnf7aPw2fDEmTIzg3EWeatFPTxs6KKUa9Ta77QQiJ5TKlw4Qpdx4jPEgcAgc9A2fKkNkRBUvDCL/lLvWPXRLy3+psuK5jc3eCADHaPLeSeDRLA53Fw14ImRs=,iv:FGkk20RP2MYT+4WRB4MuUcgK+E2C5htaIzHl6NMa9ZY=,tag:sr7hDqrmJIed0+4nqAih2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
