# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      neededForBoot = true;
      options = [ "defaults" "size=25%" "mode=755" ];
    };
    
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "nodev" "nosuid" "noexec" "relatime" "umask=0077" ];
    };
  
  fileSystems."/nix" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };
        
  fileSystems."/nix/state/etc" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/nix/state/home/alex" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=home/alex" ];
    };

  fileSystems."/nix/state/home/nicklor" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=home/nicklor" ];
    };

  fileSystems."/nix/state/root" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix/state/var" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/nix/state/var/log" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=var/log" ];
    };
  
  fileSystems."/mnt/drive_a" = {
    device = "/dev/mapper/crypto-drive-a";
    fsType = "btrfs";
    options = [
      "nofail" "relatime"
      "compress=zstd"
      "x-gvfs-name=Drive%20A" "x-gvfs-show"
      "noauto" "x-systemd.automount"
    ];
  };

  fileSystems."/mnt/drive_f" = {
    device = "/dev/mapper/crypto-drive-f";
    fsType = "xfs";
    options = [
      "nofail" "relatime"
      "x-gvfs-name=Drive%20F" "x-gvfs-show"
      "noauto" "x-systemd.automount"
    ];
  };

  swapDevices = [ ];

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/34019df5-2e72-4c07-aa50-6551dde347ec";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
