#!/bin/sh

docker run -itd --rm --privileged \
    --pull always \
    --name=redroid14 \
    -v ~/.local/share/redroid/14:/data \
    -p 5555:5555 \
    redroid/redroid:14.0.0-latest \
    androidboot.redroid_width=1920 \
    androidboot.redroid_height=1080 \
    androidboot.redroid_dpi=200 \
    androidboot.redroid_fps=90

adb connect localhost:5555
sleep 10s

scrcpy -s localhost:5555

docker stop redroid14
