config_bd9z: ENC[AES256_GCM,data:OgWRYxkt8yQV3qoq8P9+Q2ftNNYojhwT3rc26yhKQ9EbvEZD22RXpkBIoAAuBo8eOO5mIs+3dAwfrrB681HPwBgDoHbgoAP/wnotGhWbwlsVYBaIJtoehzutZv2oF3WzTNXWV8MIzXpfqKpttmRXj/58WHkYmTtW6WoJCWOfd/ARDnIRL3JNu0Gn9vKJ6BlxVfpG9+wFjc6pvN5VPnEb8ViOrus96ofPwgZVs2fN7azDBUW0z5RO/5I6Nz/1zIb1rlQXP/kimpyLxtvjCJ/CWqt+qGMe+tzow4jCwJNYYAD5dA==,iv:5LKzNhVtE0atthcNeXo3GnQslVgd6f5hMLnkwQACRMY=,tag:znbaXW5j9Da2JuBDIt+SvQ==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTTI1REcyLy82L3Q5Yjc3
            b25GWHcxbWsxbVpERCtXYnhUOW5lTWtBcWpNCnJHbUJFcE5wWXIwSzRaYkhGVGcv
            TzQ3NVBldnVlV3RVaFpUM1JOZUpaaEEKLS0tIGp1QXQvakd4QXU0UlFDNmtJMWZH
            VDc2cW9hZDJ1TVgwMFJqa1AvdUZCSTQKlraAMDlpXOnisBJbpzflk2wrE6/S3Ld1
            HjPvmCCegF/6pbItm1OFSmgHE4HM3jzsokWq/t/zhJVqqq2jgiHDwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T08:22:40Z"
    mac: ENC[AES256_GCM,data:okFnsHXPaeHcud8XPad0pukzWrE2TU2MaPEQh6L0d6V0Ru73AegR/fJTvxuiI1jmoq/bRuq1QkrdclOouX/UqgLCOJnB1bQOQn2nA530KJwAkk1uF4mFO/Rl9iqG6JwS025DuKi6uaKlnuO6XhckwvkofkeOW/WNuHzTLCeZZM4=,iv:LY5pZHGMCGqRI4hMo3vT7e5flVH5i8gFtHatv5eU+jU=,tag:tn7zgPQ2eF/fwZU9nl9yvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
