config_bd9z: ENC[AES256_GCM,data:09UXy+BRCMwjQVQvAPTur2t1bt3EHW2xJCsdWFKZetAPL/xzVEcazNfxjI6xOFiW4iKYb7vMc3WMts/f9+wAZG9X+6+nh5ocZXv4PfBXJfSY4IW7COErExaqJqRuv2bFTFFEnhTmq6w74bRm6Tt3VHhMqotNpREl2sv1BUSBRXxNG2scfka6IFurJ+tEP23Rhq38iveKFvUkpFrFwc2HNX+i0fUcbSJ4intagE18h3ieY2iSeOOs5XlHqgF/YSaaNyMLoj0Ez9UgHmQJj8V+aFrPUd+M+dcW/6q2Syex3rjUSA==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:H0gls0ECD+NjVhfpf7rgcA==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWHZZRVV4K0hScDR0SFda
            V3ZwTzNER0p4M1ViOGI5N1pPZEhkUjY2WlI4CjQ4dGlyS1pPR3JCVmNiY0FsdDBl
            aklSYThJUUd5WDJRSzF2ZjVhR2RVbFUKLS0tIGNJSTA1SXZjMGdzaWxLK0FjTEZF
            TmlwWENLZVhVU3ZNYmJTczdtK2lsZGMKhhRRuydpTYlCPJDe7+yhPHswZgKftaZV
            o4A14jhQ0K0vYUYtBWpDAjFBW/bmXVRzznEK192gK3XB43qIlQZPow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T20:37:16Z"
    mac: ENC[AES256_GCM,data:6u2yIV9p4YXnEl03qz1T1G0miOWvPkQsrdYglMFeYdDuubLQxqxep6alKSaSzRchY0dmCt0PnJaeWcEefQRHRh2fcC/dpGzUO5klOXtq4CUz92zU9bnmABiT8uJgaCjyNR79JZy6QzvI7F7Ck7UN7FKaZkEHnduyyZmYiD1l87E=,iv:kswntacbN8ZLW8GoFvmYj8J5UW8JRj+6awWfszGHMO4=,tag:Qt+2yhZ+SrtmEvKH+CkXzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
