config_bd9z: ENC[AES256_GCM,data:JqjtNtD8ZGBm1Lewn6n04Fd9tYY3Wz/SbsQUgKWkBFFXe983l34mLlHteYFdb11zs187eaot3zNZGHwxKck9KclVNhjHLRuH2CFKFxKM1jmUN1/btAZ3MvDZqLcOdheUYdmOli8Ow2uepN9WnC1lM3jqnonbcj+zyue5awVr9zzm/AwjAZr3dPaZ+dZUM21+ZWMMYa0wd5wjJlRLsm0/T08e4lWW+bG+G96B13QoD+THXc1JylWi8V6GFVVpH75yxH4u0iB5l2b9zuBX4JIpKCEbDzHHtEY7XISqdYEEf5Tbow==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:BPSCVG7j/o0RjlgsBtwDqw==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTTI1REcyLy82L3Q5Yjc3
            b25GWHcxbWsxbVpERCtXYnhUOW5lTWtBcWpNCnJHbUJFcE5wWXIwSzRaYkhGVGcv
            TzQ3NVBldnVlV3RVaFpUM1JOZUpaaEEKLS0tIGp1QXQvakd4QXU0UlFDNmtJMWZH
            VDc2cW9hZDJ1TVgwMFJqa1AvdUZCSTQKlraAMDlpXOnisBJbpzflk2wrE6/S3Ld1
            HjPvmCCegF/6pbItm1OFSmgHE4HM3jzsokWq/t/zhJVqqq2jgiHDwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T21:39:48Z"
    mac: ENC[AES256_GCM,data:k4rU41CW4r4PiLpvvQiHwdL34rGGC3DdlWeuTTZx9fZKzZ+18sYGMj5b6E2qu4XNnguOD6nCXpHBs7P5mBauoqYzjzt5QRL+8kaO0O+s728wBSITdRe2kk+Ry6vyYd+9fbdsgOSprDXV1EkO4nRKWSYo1ZRZckwlg7qhLQu8I80=,iv:JyvhN3SCgarFR3d32vDKcrDMscrzMDrOqMM1hUQbJU4=,tag:N6HyAGe+ghj5F0jXv+KVLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
