config_bd9z: ENC[AES256_GCM,data:Z4kjVq9nVrloZ1WBTYgO72rcvwT39kJcslEmN0P1yMz3AHsSBfrXuSH8eLOMj+cVQKs0dE9dALudsaWf6vCQScZLdp8FYgnopUT+2Ln8ICcRwPEQeZ+KyLc++Mz75IzZpcdxaykH1LKxjhb8M8UwnNyXQ9NFqvgUrjtd5o6Z4i3vUuy+0J6BSG7eSWAWRmNmztwcKPIqVo3hrZg65orZaNki85LgyTu8kUQzH52vKvQ5Qf+h5k0GMQpq2M7kTZWJ7cKs4/ErLUjB8QtOPj2ZPkWpW5N+OvBjYp6cM94/tYPXXQ==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:JIxkOn2eBdcJAPoX+yncVA==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZnhGQzEvQzFjZTBRajZL
            L3ZTSHhrM2tDcUI4S0h0SDJjL3Y1WGhLK0VNCjNMY05DUWhVNkJZaC8yWk9TTi9w
            Q1VGa05ZWTlnSmFkK2RIRzNWcHZGa28KLS0tIHU0aHRnSWk0eEoyelF6K3RlMEtC
            V1REUFJHaXZOMWlNdUppOHozWktZSkUKjmHFxhOic+0VuqTP/16MXpVEIuoUSOlU
            THKGDPrN3bnSI8JtRT5209M3OL+trNDHLJGpto9z9X/4okWqvGzS8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T19:45:01Z"
    mac: ENC[AES256_GCM,data:DtmYnl+mCEZvsAAOj513Tt+dnQG2oBjRRU9aPsRC5o5/xiFYE0U1q36A5uFTiwR7QNRpUGgaTmGisrPOnzRL2QNhFlLMrsTSkUurouZmdmQyT5l+EcFVPrgfGEfgeBuQ0YJUqVmz5E7sHtuP5nKaxoFZbFHyFICB9E22MMK5//M=,iv:wzFZmqqTrJouB5utVFnznAx3eBGM3wtX8ptyefKkwp0=,tag:RHp5wQm++wymk24odfNsCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
