config_bd9z: ENC[AES256_GCM,data:ldU5gw5p4K1gOegUWFBAphEBCux0x5V6FaqPLctYx5OvsNn1N8jfGfsm4H+9jw5e7ZYrJAWUXES6QUHhIebtdwceYPuC4GnkdGMJQmAcjc3Js7Pp0tAmLejdq3iiBIySeMaENqcc+LKQHprrZh5EXul9l+zK/fmz1ykTTxbfHqYEcKxFCmh7ItdquPqKWkzx0szqIPqpf8opCd9qnTC8l18QUF4nkG10VmmX4DeANh4cf0vS/FqWKdEgvDGmjH/vRKAyCwmyJR3bQMmepHwFQzpPZmPBA1SCOz5HowjXUVRGXg==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:JuY570tv8P6WWe1bRkyXxw==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdEc1Vm91VDBvVTNtVzR6
            MkZ0WldzaVRod2ZmdFovYzJocStaL3Q1OG5jCjdrQjE2d2lZWUF4UWNBWTA1bld6
            Q28rVnVsWUNpQnk2LzdYTzFUQnY4bGsKLS0tIEdtcms2NjZkdzFmT0VWaUYzZjlp
            ZXJaMVl6a0xkejdJdGcyWVJ1a1VMcTgK30f/hF6Z0Jz8eJm862xljy8ZRqxdft0z
            Mmp3ylenlz5sYAFQswZmcMiDPDVXf4sookSTVhlP9AlYTB5RMLiHWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T19:46:41Z"
    mac: ENC[AES256_GCM,data:qxYiW9ImD79jBixTYb3e6WryB8W60EDlNEl085uCGqMOI1oILR+PHeDWXECS2VCZA0hsHgZoDlhWyuLRctc2ZNndjSSH1bcIUxgWuALbbT4sZUYTmfecfx2yokEOO2HCnQKv4fHOvvmhZlSwaPvVGjwLhdsCfZb2EdTU34oMgAE=,iv:BVk/0eCC1YvoeBKoGjMab9m30cTfDtSERrUCNdesp1c=,tag:0YrZw05H+DuBFC6TM1jd2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
