config_bd9z: ENC[AES256_GCM,data:X32YiLt+qe2hefagtiqBw5o3urNUWlcr01qYaU93jSwoIAWj4jZpfQQI6lODNMymSZSB10+efVmX4YSvdCIICYtVCwzIX2vSbeG5sj7RqnIVhM2Me1MqKLgdzAB/HKKfVJ8IirMIwhKy0+xa3SVJrMf7Z7QmLKen31Nd7bxox3bRHTe8yI44CAmHtI0cAbzX5xbDg5nZKcRoqyjK23+jQ8d+KNXuI7ZQDHS6/ZkrlsMUFSebb6vHAq6mmNprTtJKUXsMu14R5FNQGpA24GS7GxNoDKm++l4GMar87xg7FVDmVQ==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:zeIE0smHKGTv+aPQL70AOQ==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTDIxeDFZSXQ5SEJDNU95
            OXNuMkxNdnlKdUtoakcvK2lPczU1REQzUkJnCklBZ1lnRUdUUGdGUDRYYTM1Q1RF
            QUorMmJFaUlZS3U5NzZYenBFZlFiSFUKLS0tIDY5S3ovY0J6N3NOSUdEQnZZRWQv
            dll3RVo2WWV1WGpaTHppU0VKdzRsSHMKkPUjHQaK8/iEirbYGZKSt3n5ka/ljPS8
            6fjPscN/kfXcstducy8QSMFTRUVcMqK2ye9HE4R0XFKY5Jq/rd2Wfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T19:38:51Z"
    mac: ENC[AES256_GCM,data:NBhR1Ftao3VrgN1a5N3rbQBB75GaRBiv+thpoqUeOADD2CuBEmCJXILqz9U3KCG/lOGm6BtClUC5dNv+o7VuJ3Mt+a1o0WG/kmBl1jNOA0R0M46c318/g2oML5e/ZZyf2VOeDVxar0zi3ZRKbeYfyX55wOQGh9w8IAA8xNjAxWY=,iv:HhHkHSdbhbLA31lUdc6b8QjVA2/nvh5x9CGpXAFC7eY=,tag:tqcmg0YKthy+eJdMr54QRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
