config_bd9z: ENC[AES256_GCM,data:N9+M+nNpz1xoongu13ScW94UOMygrWRd5yMd46hEnCFLk/04UrXPL06SxXONPXadj/hUSqiQuxUjaZLlhs3Gp9okXevydWn9HpAe/m5VT2MSGBzBYFxkUOJ8Tgd9Nq5TtwWMivNJtH4SaexERaOcmuegsvfZP6tQsxkLWm9Lhjg3mi95XsYCQM+7WMxp2bmnJmEbIYo8C7lF9HHQglz0/MDRQlULcaJFTSyHw3lMlKh5QTxCbO2vN5ZuwfRoOZg+4j5GKC+ZbC2VHSW6ev0i0X/dHQ7Kc+lDn56SSs0yOEzAcw==,iv:ksvgBUiVORw5ASuqEgAGzKJFcP89ov780AoC/ql+wpM=,tag:vtm3D0ekXxIt2DKFGh/A8g==,type:str]
sops:
    age:
        - recipient: age1zuqn8tq3sqwulv4szyjh53ytfrznpj59whzslcqfjlyvhudqqe2q6y5jr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFVKTEw4czlRb0FEM0Fr
            cW1sN3JRSlJGc2RCeko1dEZxdUd4dmRLWW0wCjFweGE3S3FybXpXQnlveTBQUm9I
            OWUrT1pNSlRnaVZiS3NzbUVpUEhjQ00KLS0tIE13dkd3OThMWUJsS3EyVWE1RnBh
            bnBEbCtNOWRhVlZUbFB6eUsycWNNcDAKw896OW79X7dNqyG9TUQxc9LxyXqfqv+S
            SscKy6Mrn09kJcr2l7kqHG/pP/6mjfb62bIXh5MWBTAcr0HcCSyfwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T19:29:48Z"
    mac: ENC[AES256_GCM,data:iiDMy1B/zOj8Lw+uUk6l/RWDZFZS/X6tkBG1fbO1RZC88QdI9eB46GaE2/6PX2gljLfX1Ux8gh/2of8iAkFNpaXcpHwyHEcO5zgi8+s2RjUyiUxcpk53tjwc0jVdGQXd0m+OzanfzZsiawVyv7V/tnN1UyRJ2t86Mz1xg62WknE=,iv:sfi9FMdUfeSZRh8LilkVNYIxUwPumUChF4nDE26r6Ic=,tag:zK5Xb+8TkYmXUpc6xavtwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
